### ISSUE TITLE
Received at email

### ISSUE THREAD

**Issue by ishahmiri** [zendesklabs/zignatures#13]
Hi there!

Is there anyway to use your  app to make it so that we can automatically set different ticket signatures depending on what support email the ticket was received at?

**Comment by Sarapulov** [comment]
thanks for the feedback.

this is challenging one, as support email is not easily accessible via Liquid which Zignatures heavily rely on.

You can possibly map a support email to, say, a dropdown field and then construct the signature code using a value from that dropdown. But this should be handled by a different solution.

Otherwise, I can see this as valid feature request for this app.

**Comment by ishahmiri** [comment]
Hey Andrey,

Thanks for the reply! So you’re saying to:

1) Make a trigger to assign a custom ticket field based on the received at support email. 
2) Add a placeholder code to the signature, the placeholder code being the above custom ticket field

Let me know, thank you! 

	
Iman Shahmiri
Director of Systems, The I IYV
(818) 282-2167
thehyv.net <http://thehyv.net/>
Los Angeles USA
 <http://twitter.com/the_hyv>	 <http://instagram.com/thehyv?utm_source=ig_profile_share&igshid=1f7osb9ywng48>

**Comment by Sarapulov** [comment]
Hi Iman, yes. That should work.

**Comment by ishahmiri** [comment]
Thanks for your help here :)


	
Iman Shahmiri
Director of Systems, The I IYV
(818) 282-2167
thehyv.net <http://thehyv.net/>
Los Angeles USA
 <http://twitter.com/the_hyv>	 <http://instagram.com/thehyv?utm_source=ig_profile_share&igshid=1f7osb9ywng48>
