### ISSUE TITLE
App couldn't be deactivated if signature text is empty

### ISSUE THREAD

**Issue by ifcologne** [zendesklabs/zignatures#5]
I'm just preparing the launch and found an interesting side effect. 
(Mac/Chrome 60)

1. Installed Zignatures app in Zendesk
2. Delete the default signature in the first screen - leave signature text blank: ok (it's possible to save)
3. Try to deactivate app: Error: `could not deactivate Zignatures`
4. Try again. Also from overview contextmenu - nothing. _Panic_ :)
5. Try a workaround. Check Deactivate display of app in sidebar option: Error: `Signature text is required`
6. Added something in the signature, saved: `ok`
7. Deactivate App: `ok`
8. Thankful again. :)

So, adding the required attribute to the first setup screen might fix the issue, allowing to deactivate the app without needing a valid signature text would be even better.

**Comment by Sarapulov** [comment]
hm.... this seems like App Framework Issue rather than App itself.

I was able to replicate it (GIF below). Looks like required fields in app settings are ignored at first installation. Which doesn't seem right to me. I will report this problem to Apps Team at Zendesk.

I believe this issue doesn't really affect the app behaviour. Signature template is expected to be in the app settings anyway. Otherwise, the app is useless.

*Able to install the app with mandatory settings missing*
![](https://cl.ly/203e3V0u0l1Z/Screen%20Recording%202017-08-19%20at%2002.16%20PM.gif)

*Unable to deactivate the app when mandatory settings are missing. Error message is not obvious*
![](https://cl.ly/2l450V1o073w/Screen%20Recording%202017-08-19%20at%2002.21%20PM.gif)

**Comment by Sarapulov** [comment]
@ifcologne 
With all your contributions here I would love to know more about your use case and how you plan to use this app? Is this something you will be willing to share?

**Comment by ifcologne** [comment]
Sure. 

It's a combination - being able to use more personalized signatures (for one of several departments using Zendesk) and using ticket information (ticket.id) to invite customers to a follow up feedback survey.

We don't use the built-in Zendesk solution so we needed a way to get access to the ticket id. It's not available from the agent signature so Zignatures is a solution to get around. 
B.t.w. - have I asked for **Markdown support** yet? :)

We now use Zignatures to decide whether or not to include the feedback link and what kind of additional dynamic content. The option to disable the signature if you have lengthy back and forth conversations is a plus.

**Comment by Sarapulov** [comment]
nice! thanks for sharing.
Could imagine app feature like "stop signing after X public comments" which can automate your workflow further. What do you think?

**Comment by Sarapulov** [comment]
re Markdown support, it is possible to add such support, but it's quite some logic to build. The app is expecting Agent to use Rich text editor at all time. Why would you need markdown if you can use HMTL?
